# Generated by Django 5.2.13 on 2026-04-26 00:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compositions', '0001_initial'),
        ('core', '0001_initial'),
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QCMExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('melanger_questions', models.BooleanField(default=True, verbose_name='mélanger questions')),
                ('melanger_choix', models.BooleanField(default=True, verbose_name='mélanger choix')),
                ('afficher_resultat_immediat', models.BooleanField(default=False, verbose_name='résultat immédiat')),
                ('mode_notation', models.CharField(choices=[('classique', 'Classique (bonne réponse = points)'), ('penalite', 'Avec pénalité (mauvaise réponse = -points)'), ('partielle', 'Partielle (réponses partielles)')], default='classique', max_length=20, verbose_name='mode de notation')),
                ('points_bonne_reponse', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='points bonne réponse')),
                ('penalite_mauvaise_reponse', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='pénalité mauvaise réponse')),
                ('nb_questions_par_page', models.PositiveIntegerField(default=1, verbose_name='questions par page')),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qcm_config', to='exams.exam')),
            ],
            options={
                'verbose_name': 'configuration QCM',
                'verbose_name_plural': 'configurations QCM',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texte', models.TextField(verbose_name='texte de la question')),
                ('explication', models.TextField(blank=True, verbose_name='explication')),
                ('difficulte', models.CharField(choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], default='moyen', max_length=20, verbose_name='difficulté')),
                ('tags', models.JSONField(default=list, verbose_name='tags')),
                ('est_publique', models.BooleanField(default=False, verbose_name='publique')),
                ('generee_par_ia', models.BooleanField(default=False, verbose_name='générée par IA')),
                ('source_cours', models.TextField(blank=True, verbose_name='source du cours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_creees', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='core.matiere')),
            ],
            options={
                'verbose_name': 'banque de questions',
                'verbose_name_plural': 'banques de questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QCMExamQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('points', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='points')),
                ('qcm_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='qcm.qcmexam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_associations', to='qcm.questionbank')),
            ],
            options={
                'verbose_name': "question d'examen QCM",
                'verbose_name_plural': "questions d'examen QCM",
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texte', models.TextField(verbose_name='texte du choix')),
                ('est_correct', models.BooleanField(default=False, verbose_name='est correct')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('explication', models.TextField(blank=True, verbose_name='explication')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='qcm.questionbank')),
            ],
            options={
                'verbose_name': 'choix',
                'verbose_name_plural': 'choix',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='QCMAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choix_selectionnes', models.JSONField(default=list, verbose_name='choix sélectionnés')),
                ('est_correct', models.BooleanField(default=False, verbose_name='est correct')),
                ('points_obtenus', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='points obtenus')),
                ('temps_reponse_secondes', models.PositiveIntegerField(default=0, verbose_name='temps de réponse (s)')),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qcm_answers', to='compositions.compositionsession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='qcm.questionbank')),
            ],
            options={
                'verbose_name': 'réponse QCM',
                'verbose_name_plural': 'réponses QCM',
                'unique_together': {('session', 'question')},
            },
        ),
    ]
