# Generated by Django 5.2.13 on 2026-04-26 00:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_export', models.CharField(max_length=50, verbose_name="type d'export")),
                ('format_export', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('pdf', 'PDF'), ('json', 'JSON')], max_length=10, verbose_name='format')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='exports/%Y/%m/', verbose_name='fichier')),
                ('parametres', models.JSONField(default=dict, verbose_name='paramètres')),
                ('nb_lignes', models.PositiveIntegerField(default=0, verbose_name='nombre de lignes')),
                ('statut', models.CharField(default='en_cours', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'export de données',
                'verbose_name_plural': 'exports de données',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('submit', 'Soumission'), ('correct', 'Correction'), ('export', 'Export'), ('download', 'Téléchargement'), ('cheat', 'Tentative de triche'), ('assign', 'Attribution'), ('verify', 'Vérification')], max_length=20, verbose_name='action')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Attention'), ('critical', 'Critique')], default='info', max_length=20, verbose_name='sévérité')),
                ('resource_type', models.CharField(max_length=50, verbose_name='type de ressource')),
                ('resource_id', models.CharField(blank=True, max_length=100, verbose_name='ID ressource')),
                ('description', models.TextField(verbose_name='description')),
                ('details', models.JSONField(default=dict, verbose_name='détails')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='session ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='horodatage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "journal d'audit",
                'verbose_name_plural': "journal d'audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='audittrail__user_id_4f33b0_idx'), models.Index(fields=['action', '-timestamp'], name='audittrail__action_f1f7ad_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audittrail__resourc_f088e9_idx')],
            },
        ),
    ]
