# Generated by Django 5.2.13 on 2026-04-26 00:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(verbose_name='URL du webhook')),
                ('secret', models.CharField(blank=True, max_length=128, verbose_name='secret')),
                ('events', models.JSONField(default=list, verbose_name='événements')),
                ('est_actif', models.BooleanField(default=True, verbose_name='actif')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('derniere_reponse', models.PositiveIntegerField(blank=True, null=True, verbose_name='dernier code HTTP')),
                ('nb_echecs', models.PositiveIntegerField(default=0, verbose_name='échecs consécutifs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'webhook',
                'verbose_name_plural': 'webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=50, verbose_name='événement')),
                ('payload', models.JSONField(verbose_name='payload')),
                ('response_status', models.PositiveIntegerField(default=0, verbose_name='code HTTP')),
                ('response_body', models.TextField(blank=True, verbose_name='réponse')),
                ('succes', models.BooleanField(default=False, verbose_name='succès')),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.webhookendpoint')),
            ],
            options={
                'verbose_name': 'livraison webhook',
                'verbose_name_plural': 'livraisons webhooks',
                'ordering': ['-delivered_at'],
            },
        ),
    ]
