# Generated by Django 5.2.13 on 2026-04-26 00:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, verbose_name='nom')),
                ('niveau', models.CharField(max_length=20, verbose_name='niveau')),
                ('section', models.CharField(blank=True, max_length=100, verbose_name='section / filière')),
                ('annee_academique', models.CharField(max_length=20, verbose_name='année académique')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'classe',
                'verbose_name_plural': 'classes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_feedback', models.CharField(choices=[('eleve_prof', 'Élève → Professeur'), ('prof_eleve', 'Professeur → Élève'), ('eleve_plateforme', 'Élève → Plateforme')], default='eleve_prof', max_length=20, verbose_name='type')),
                ('note', models.IntegerField(choices=[(1, 'Très mauvais'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Excellent')], default=4, verbose_name='note')),
                ('commentaire', models.TextField(verbose_name='commentaire')),
                ('est_anonyme', models.BooleanField(default=False, verbose_name='anonyme')),
                ('est_public', models.BooleanField(default=False, verbose_name='public')),
                ('est_lu', models.BooleanField(default=False, verbose_name='lu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(choices=[('MATHS', 'Mathématiques'), ('PC', 'Physique-Chimie'), ('SVT', 'Sciences de la Vie et de la Terre'), ('FRANCAIS', 'Français'), ('ANGLAIS', 'Anglais'), ('HIST_GEO', 'Histoire et Géographie'), ('PHILO', 'Philosophie'), ('ESPAGNOL', 'Espagnol'), ('ALLEMAND', 'Allemand'), ('TIC', "Technologie de l'Information et de la Communication")], max_length=200, verbose_name='nom')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('niveaux', models.JSONField(default=list, verbose_name='niveaux concernés')),
                ('couleur', models.CharField(default='#6366F1', max_length=7, verbose_name='couleur')),
                ('icone', models.CharField(blank=True, max_length=50, verbose_name='icône')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'matière',
                'verbose_name_plural': 'matières',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=100, unique=True)),
                ('valeur', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255, verbose_name='titre')),
                ('type_evenement', models.CharField(choices=[('examen', 'Examen'), ('composition', 'Composition'), ('correction', 'Séance de correction'), ('rattrapage', 'Rattrapage'), ('autre', 'Autre')], default='composition', max_length=20, verbose_name='type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('date_debut', models.DateTimeField(verbose_name='début')),
                ('date_fin', models.DateTimeField(verbose_name='fin')),
                ('lieu', models.CharField(blank=True, max_length=255, verbose_name='lieu')),
                ('salle', models.CharField(blank=True, max_length=100, verbose_name='salle')),
                ('couleur', models.CharField(default='#6366F1', max_length=7, verbose_name='couleur')),
                ('est_public', models.BooleanField(default=False, verbose_name='public')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'événement calendrier',
                'verbose_name_plural': 'événements calendrier',
                'ordering': ['date_debut'],
            },
        ),
    ]
