# Generated by Django 5.2.13 on 2026-04-26 00:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AICorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('corrige_type_text', models.TextField(blank=True, verbose_name='texte du corrigé type')),
                ('copie_text', models.TextField(blank=True, verbose_name='texte de la copie')),
                ('prompt_envoye', models.TextField(blank=True, verbose_name='prompt envoyé')),
                ('reponse_ia', models.TextField(blank=True, verbose_name='réponse IA')),
                ('note_proposee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='note proposée')),
                ('details_json', models.JSONField(default=dict, verbose_name='détails JSON')),
                ('model_utilise', models.CharField(blank=True, max_length=50, verbose_name='modèle utilisé')),
                ('tokens_utilises', models.PositiveIntegerField(default=0, verbose_name='tokens utilisés')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('erreur', 'Erreur')], default='en_attente', max_length=20, verbose_name='statut')),
                ('erreur', models.TextField(blank=True, verbose_name='erreur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'correction IA',
                'verbose_name_plural': 'corrections IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_number', models.PositiveIntegerField(verbose_name='numéro de question')),
                ('note_partielle', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='note partielle')),
                ('commentaire', models.TextField(verbose_name='commentaire')),
                ('erreurs', models.JSONField(default=list, verbose_name='erreurs identifiées')),
                ('points_forts', models.JSONField(default=list, verbose_name='points forts')),
            ],
            options={
                'verbose_name': 'détail de correction',
                'verbose_name_plural': 'détails de correction',
                'ordering': ['question_number'],
            },
        ),
    ]
