# Generated by Django 5.2.13 on 2026-04-26 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('compositions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicorrection',
            name='resultat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_correction', to='compositions.resultat'),
        ),
        migrations.AddField(
            model_name='correctiondetail',
            name='ai_correction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='ai_engine.aicorrection'),
        ),
    ]
