# Generated by Django 5.2.13 on 2026-04-26 00:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compositions', '0001_initial'),
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlagiarismCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('erreur', 'Erreur')], default='en_attente', max_length=20, verbose_name='statut')),
                ('seuil_similarite', models.DecimalField(decimal_places=2, default=75.0, max_digits=5, verbose_name='seuil similarite (%)')),
                ('nb_paires_analysees', models.PositiveIntegerField(default=0, verbose_name='paires analysées')),
                ('nb_paires_suspectes', models.PositiveIntegerField(default=0, verbose_name='paires suspectes')),
                ('rapport_global', models.JSONField(default=dict, verbose_name='rapport global')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('declenche_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_checks', to='exams.exam')),
            ],
            options={
                'verbose_name': 'vérification plagiat',
                'verbose_name_plural': 'vérifications plagiat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlagiarismReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='plagiarism_reports/%Y/%m/', verbose_name='PDF')),
                ('resume', models.TextField(blank=True, verbose_name='résumé')),
                ('recommendations', models.TextField(blank=True, verbose_name='recommandations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='plagiat.plagiarismcheck')),
            ],
            options={
                'verbose_name': 'rapport plagiat',
                'verbose_name_plural': 'rapports plagiat',
            },
        ),
        migrations.CreateModel(
            name='PlagiarismPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similarite_globale', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='similarité (%)')),
                ('similarite_par_question', models.JSONField(default=dict, verbose_name='similarité par question')),
                ('niveau_suspection', models.CharField(choices=[('faible', 'Faible (<30%)'), ('modere', 'Modéré (30-60%)'), ('eleve', 'Élevé (60-80%)'), ('critique', 'Critique (>80%)')], default='faible', max_length=20, verbose_name='niveau')),
                ('phrases_communes', models.JSONField(default=list, verbose_name='phrases communes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_as_1', to='compositions.compositionsession')),
                ('session_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_as_2', to='compositions.compositionsession')),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='plagiat.plagiarismcheck')),
            ],
            options={
                'verbose_name': 'paire plagiat',
                'verbose_name_plural': 'paires plagiat',
                'ordering': ['-similarite_globale'],
                'unique_together': {('verification', 'session_1', 'session_2')},
            },
        ),
    ]
