# Generated by Django 5.2.13 on 2026-04-26 09:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correction', '0001_initial'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctioncopie',
            name='json_resultat',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='correctioncopie',
            name='note_ia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='correctioncopie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='correctioncopie',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exams.exam'),
        ),
        migrations.AlterField(
            model_name='correctioncopie',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='correctioncopie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='submissions/%Y/%m/'),
        ),
    ]
