# Generated by Django 5.2.13 on 2026-04-26 00:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse email')),
                ('first_name', models.CharField(max_length=150, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=150, verbose_name='nom')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('country', models.CharField(default='France', max_length=100, verbose_name='pays')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('conseiller', 'Conseiller Pédagogique'), ('professeur', 'Professeur'), ('eleve', 'Élève / Étudiant')], default='eleve', max_length=20, verbose_name='rôle')),
                ('niveau', models.CharField(blank=True, choices=[('primaire', 'Primaire'), ('secondaire', 'Secondaire'), ('universitaire', 'Universitaire'), ('professionnel', 'Formation Professionnelle'), ('entreprise', 'Entreprise')], max_length=20, verbose_name='niveau')),
                ('classe', models.CharField(blank=True, max_length=100, verbose_name='classe / promotion')),
                ('matricule', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='matricule')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='photo de profil')),
                ('bio', models.TextField(blank=True, verbose_name='biographie')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('preferred_language', models.CharField(default='fr', max_length=5)),
                ('dark_mode', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('school', models.CharField(blank=True, max_length=200)),
                ('specialite', models.CharField(blank=True, max_length=200)),
                ('total_points', models.IntegerField(default=0)),
                ('badges', models.JSONField(default=list)),
                ('completed_exams', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('rank', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
