# Generated by Django 5.2.13 on 2026-04-26 00:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=300, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('type_exam', models.CharField(choices=[('composition', 'Composition'), ('examen', 'Examen'), ('devoir', 'Devoir'), ('concours', 'Concours'), ('eval_prof', 'Évaluation Professeur')], default='composition', max_length=20, verbose_name='type')),
                ('duree_minutes', models.PositiveIntegerField(default=60, verbose_name='durée (minutes)')),
                ('date_debut', models.DateTimeField(verbose_name='date de début')),
                ('date_fin', models.DateTimeField(verbose_name='date de fin')),
                ('note_maximale', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='note maximale')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='coefficient')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='brouillon', max_length=20, verbose_name='statut')),
                ('approval_status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name='statut approbation')),
                ('est_public', models.BooleanField(default=False, verbose_name='public')),
                ('instructions', models.TextField(blank=True, verbose_name='instructions')),
                ('anti_cheat_active', models.BooleanField(default=True, verbose_name='anti-triche actif')),
                ('camera_required', models.BooleanField(default=True, verbose_name='caméra obligatoire')),
                ('fullscreen_required', models.BooleanField(default=True, verbose_name='plein écran obligatoire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_approved', to=settings.AUTH_USER_MODEL)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='core.classe')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams_crees', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='core.matiere')),
            ],
            options={
                'verbose_name': 'épreuve',
                'verbose_name_plural': 'épreuves',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_fichier', models.CharField(choices=[('epreuve', 'Épreuve'), ('corrige_type', 'Corrigé Type'), ('annexe', 'Annexe')], max_length=20, verbose_name='type de fichier')),
                ('fichier', models.FileField(upload_to='exams/%Y/%m/', verbose_name='fichier')),
                ('nom_original', models.CharField(max_length=255, verbose_name='nom original')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='exams.exam')),
            ],
            options={
                'verbose_name': "fichier d'épreuve",
                'verbose_name_plural': "fichiers d'épreuve",
            },
        ),
        migrations.CreateModel(
            name='ExamAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_crees', to=settings.AUTH_USER_MODEL)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to='core.classe')),
                ('eleve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exams.exam')),
            ],
            options={
                'verbose_name': "attribution d'épreuve",
                'verbose_name_plural': "attributions d'épreuves",
                'unique_together': {('exam', 'classe'), ('exam', 'eleve')},
            },
        ),
    ]
