# Generated by Django 5.2.13 on 2026-04-26 00:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AntiCheatLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_event', models.CharField(choices=[('tab_change', "Changement d'onglet"), ('fullscreen_exit', 'Sortie plein écran'), ('camera_off', 'Caméra désactivée'), ('multiple_faces', 'Plusieurs visages détectés'), ('copy_paste', 'Copier/Coller'), ('right_click', 'Clic droit'), ('suspicious_movement', 'Mouvement suspect')], max_length=30, verbose_name="type d'événement")),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='cheat_screenshots/%Y/%m/', verbose_name="capture d'écran")),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='horodatage')),
            ],
            options={
                'verbose_name': 'log anti-triche',
                'verbose_name_plural': 'logs anti-triche',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='note')),
                ('note_sur', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='note sur')),
                ('mention', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('tres_bien', 'Très Bien'), ('bien', 'Bien'), ('assez_bien', 'Assez Bien'), ('passable', 'Passable'), ('insuffisant', 'Insuffisant')], max_length=20, verbose_name='mention')),
                ('appreciation', models.TextField(blank=True, verbose_name='appréciation')),
                ('details_correction', models.JSONField(default=dict, verbose_name='détails de correction')),
                ('classement', models.PositiveIntegerField(default=0, verbose_name='classement')),
                ('total_participants', models.PositiveIntegerField(default=0, verbose_name='total participants')),
                ('corrige_par_ia', models.BooleanField(default=False, verbose_name='corrigé par IA')),
                ('corrige_par_humain', models.BooleanField(default=False, verbose_name='corrigé par humain')),
                ('corrige_at', models.DateTimeField(blank=True, null=True, verbose_name='date de correction')),
                ('bulletin_pdf', models.FileField(blank=True, null=True, upload_to='bulletins/%Y/%m/', verbose_name='bulletin PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'résultat',
                'verbose_name_plural': 'résultats',
                'ordering': ['-note'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_number', models.PositiveIntegerField(verbose_name='numéro de question')),
                ('content', models.TextField(verbose_name='contenu de la réponse')),
                ('file', models.FileField(blank=True, null=True, upload_to='answers/%Y/%m/', verbose_name='fichier joint')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "réponse de l'élève",
                'verbose_name_plural': 'réponses des élèves',
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentSubmissionFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fichier', models.ImageField(upload_to='submissions/%Y/%m/', verbose_name='fichier')),
                ('page_number', models.PositiveIntegerField(default=1, verbose_name='numéro de page')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'fichier de soumission',
                'verbose_name_plural': 'fichiers de soumission',
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='CompositionSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('en_ligne', 'En Ligne'), ('sur_papier', 'Sur Papier')], default='en_ligne', max_length=20, verbose_name='mode')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('soumis', 'Soumis'), ('en_correction', 'En correction'), ('corrige', 'Corrigé'), ('exclu', 'Exclu (triche)')], default='en_attente', max_length=20, verbose_name='statut')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='début')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='soumission')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='temps passé (secondes)')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Code')),
                ('qr_token', models.CharField(blank=True, max_length=255, verbose_name='token QR')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('cheat_count', models.PositiveIntegerField(default=0, verbose_name='nombre de triches')),
                ('cheat_logs', models.JSONField(default=list, verbose_name='logs de triche')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'session de composition',
                'verbose_name_plural': 'sessions de composition',
                'ordering': ['-created_at'],
            },
        ),
    ]
