# Generated by Django 5.2.13 on 2026-04-26 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compositions', '0001_initial'),
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compositionsession',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='anticheatlog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anti_cheat_logs', to='compositions.compositionsession'),
        ),
        migrations.AddField(
            model_name='resultat',
            name='corrigeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections_effectuees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultat',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultat', to='compositions.compositionsession'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='compositions.compositionsession'),
        ),
        migrations.AddField(
            model_name='studentsubmissionfile',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_files', to='compositions.compositionsession'),
        ),
        migrations.AlterUniqueTogether(
            name='compositionsession',
            unique_together={('exam', 'eleve')},
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('session', 'question_number')},
        ),
    ]
