# Generated by Django 5.2.13 on 2026-04-26 00:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classe', models.CharField(max_length=100)),
                ('annee_scolaire', models.CharField(max_length=20)),
                ('periode', models.CharField(choices=[('T1', '1er Trimestre'), ('T2', '2ème Trimestre'), ('T3', '3ème Trimestre'), ('S1', '1er Semestre'), ('S2', '2ème Semestre'), ('AN', 'Annuel')], max_length=5)),
                ('moyenne_generale', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('rang', models.PositiveIntegerField(default=1)),
                ('appreciation_ia', models.TextField(blank=True, default='', verbose_name='synthèse pédagogique IA')),
                ('signature_numerique', models.CharField(blank=True, max_length=255)),
                ('verification_token', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to='bulletins_officiels/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BulletinLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=100)),
                ('note', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('note_max', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('moyenne_classe', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('appreciation', models.TextField(blank=True, default='')),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='bulletins.bulletin')),
            ],
        ),
    ]
