# Generated by Django 5.2.13 on 2026-04-26 00:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_saisi', models.CharField(max_length=64, verbose_name='code saisi')),
                ('ip_address', models.GenericIPAddressField(verbose_name='adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('succes', models.BooleanField(default=False, verbose_name='succès')),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de vérification')),
            ],
            options={
                'verbose_name': 'vérification de certificat',
                'verbose_name_plural': 'vérifications de certificats',
                'ordering': ['-verified_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_verification', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='code de vérification')),
                ('type_certificat', models.CharField(choices=[('excellence', "Certificat d'Excellence"), ('mention', 'Certificat de Mention'), ('completion', 'Certificat de Completion'), ('participation', 'Certificat de Participation'), ('competence', 'Certificat de Compétence')], default='completion', max_length=20, verbose_name='type')),
                ('titre', models.CharField(max_length=300, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('note_obtenue', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='note obtenue')),
                ('note_sur', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='note sur')),
                ('mention', models.CharField(blank=True, max_length=50, verbose_name='mention')),
                ('institution', models.CharField(blank=True, max_length=300, verbose_name='institution')),
                ('date_delivrance', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de délivrance')),
                ('date_expiration', models.DateTimeField(blank=True, null=True, verbose_name="date d'expiration")),
                ('signature_numerique', models.CharField(blank=True, max_length=128, verbose_name='signature numérique')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='certificates/qr/', verbose_name='QR Code')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='certificates/pdf/', verbose_name='PDF du certificat')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('revoque', 'Révoqué'), ('expire', 'Expiré')], default='actif', max_length=20, verbose_name='statut')),
                ('nb_verifications', models.PositiveIntegerField(default=0, verbose_name='nombre de vérifications')),
                ('derniere_verification', models.DateTimeField(blank=True, null=True, verbose_name='dernière vérification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_delivres', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'certificat',
                'verbose_name_plural': 'certificats',
                'ordering': ['-date_delivrance'],
            },
        ),
    ]
