# Generated by Django 5.2.13 on 2026-04-26 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certifications', '0001_initial'),
        ('compositions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='examen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='compositions.compositionsession'),
        ),
    ]
