# Generated by Django 5.2.13 on 2026-04-26 00:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('description', models.TextField(verbose_name='description')),
                ('icone', models.CharField(default='🏆', max_length=50, verbose_name='icône')),
                ('categorie', models.CharField(choices=[('academique', 'Académique'), ('participation', 'Participation'), ('excellence', 'Excellence'), ('progression', 'Progression'), ('social', 'Social'), ('special', 'Spécial')], default='academique', max_length=20, verbose_name='catégorie')),
                ('points', models.PositiveIntegerField(default=10, verbose_name='points')),
                ('condition_obtention', models.JSONField(default=dict, verbose_name='conditions')),
                ('est_actif', models.BooleanField(default=True, verbose_name='actif')),
                ('rarete', models.CharField(choices=[('commun', 'Commun'), ('rare', 'Rare'), ('epique', 'Épique'), ('legendaire', 'Légendaire')], default='commun', max_length=20, verbose_name='rareté')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'badge',
                'verbose_name_plural': 'badges',
                'ordering': ['categorie', '-points'],
            },
        ),
        migrations.CreateModel(
            name='StreakRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='série actuelle')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='plus longue série')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name='dernière activité')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "série d'activité",
                'verbose_name_plural': "séries d'activité",
            },
        ),
        migrations.CreateModel(
            name='XPAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100, verbose_name='action')),
                ('points_gagnes', models.PositiveIntegerField(default=0, verbose_name='points gagnés')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'action XP',
                'verbose_name_plural': 'actions XP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalLeaderboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periode', models.CharField(choices=[('jour', 'Journalier'), ('semaine', 'Hebdomadaire'), ('mois', 'Mensuel'), ('annee', 'Annuel'), ('all_time', 'Tous les temps')], default='all_time', max_length=20, verbose_name='période')),
                ('date_periode', models.DateField(verbose_name='date de la période')),
                ('rang_mondial', models.PositiveIntegerField(default=0, verbose_name='rang mondial')),
                ('rang_national', models.PositiveIntegerField(default=0, verbose_name='rang national')),
                ('score_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='score total')),
                ('nb_compositions', models.PositiveIntegerField(default=0, verbose_name='compositions')),
                ('nb_excellentes', models.PositiveIntegerField(default=0, verbose_name='notes excellentes')),
                ('moyenne', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='moyenne')),
                ('points_xp', models.PositiveIntegerField(default=0, verbose_name='points XP')),
                ('niveau', models.PositiveIntegerField(default=1, verbose_name='niveau')),
                ('streak_jours', models.PositiveIntegerField(default=0, verbose_name='série de jours')),
                ('pays', models.CharField(default='France', max_length=100, verbose_name='pays')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'classement',
                'verbose_name_plural': 'classements',
                'ordering': ['rang_mondial'],
                'unique_together': {('user', 'periode', 'date_periode')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('obtenu_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='obtenu le')),
                ('est_nouveau', models.BooleanField(default=True, verbose_name='nouveau')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'badge utilisateur',
                'verbose_name_plural': 'badges utilisateur',
                'ordering': ['-obtenu_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
