# Generated by Django 5.2.13 on 2026-04-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailqueue',
            name='corps_html',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailqueue',
            name='corps_texte',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailqueue',
            name='erreur',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailqueue',
            name='piece_jointe',
            field=models.FileField(blank=True, null=True, upload_to='email_attachments/'),
        ),
        migrations.AddField(
            model_name='emailqueue',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='statut',
            field=models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('error', 'Erreur')], default='pending', max_length=20),
        ),
    ]
